name: Release

on:
  release:
    types:
      - released
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore nuget packages
        run: dotnet restore Authelia-Auth/Authelia-Auth.csproj
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install JPRM
        run: python -m pip install jprm
      - name: Run JPRM
        run: python build_plugin.py --version=${GITHUB_REF#refs/*/}
      - name: Update release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/authelia-authentication*.zip
          tag: ${{ github.ref }}
          file_glob: true
      - name: Update manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update repo manifest
          file_pattern: manifest.json
